# Generated by Django 5.0.2 on 2024-05-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0004_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLog',
        ),
    ]
